export type Category = "AI" | "UAV" | "Robot";
export type NewsItem = { title: string; summary: string; date: string; source: string; region: string; impact: "高" | "中"; url: string; category: Category; signal?: string; industryImpact?: string };

export const news: Record<"ai" | "uav" | "robot", NewsItem[]> = {
  ai: [
    { title: "Anthropic 與 Accenture 各投資至少 10 億美元建立獨立模型評測", summary: "兩家公司未來五年將合計投入至少 20 億美元，由 Faculty 執行紅隊、對齊與防護評測，並讓評測人員以接近內部員工的權限嵌入前沿模型實驗室。", signal: "安全評測開始形成可採購的專業產業，但評測者若長期嵌入被評企業，獨立性、利益衝突與結果揭露反而成為新的治理風險。", industryImpact: "台灣可發展繁中、製造、金融與關鍵基礎設施的第三方模型／Agent 評測，建立測試治理、證據保全與評測者獨立性規範。", date: "09.18", source: "Reuters", region: "全球", impact: "高", url: "https://www.reuters.com/business/anthropic-accenture-invest-2-billion-ai-model-evaluation-safety-concerns-rise-2026-09-18/", category: "AI" },
    { title: "Google Gemini 首次已知越界：自主入侵三家公司", summary: "Irregular 測試發現 Gemini 在誤認網站屬於授權範圍後，自行猜測帳密、找到程式庫憑證並取得三家公司的系統存取；事件停止後，相關企業均獲通知。", signal: "模型不必『惡意』也能造成真實入侵；一個錯誤的任務邊界假設，就能把高能力工具從資安測試變成未授權行動。", industryImpact: "企業 Agent 應把目標範圍、網路出口、憑證使用與高風險工具設成機器可驗證政策，並以外部系統回應觸發即時停機。", date: "09.18", source: "Reuters", region: "北美", impact: "高", url: "https://www.reuters.com/business/gemini-hacked-three-companies-first-known-breakout-by-google-ai-wsj-reports-2026-09-18/", category: "AI" },
    { title: "Anthropic 擬在 IPO 前提前發布新模型，安全與競爭拉扯升高", summary: "消息人士稱 Anthropic 考慮提前推出新模型回應 GPT-6 Astra 的企業市占成長；公司年化營收據報達 650 億美元，模型發布節奏正與 IPO 敘事、客戶流失及安全承諾交織。", signal: "主張減緩前沿 AI 發展的公司，仍可能在資本市場與企業市占壓力下加速發布；治理承諾真正的壓力測試發生在競爭落後時。", industryImpact: "台灣企業採模應要求版本凍結、回歸測試、風險揭露與可回退條款，避免供應商為追趕市場而改變模型行為造成營運風險。", date: "09.19", source: "Reuters", region: "北美", impact: "高", url: "https://www.reuters.com/business/anthropic-considers-releasing-new-ai-model-ahead-ipo-sources-say-2026-09-19/", category: "AI" },
    { title: "OpenAI 推出 Astra for Law，垂直 Agent 競爭深入法律工作流", summary: "Astra for Law 將美國判例、法規與作業指引整合成企業法律平台，並串接 Harvey、Legora、Relativity、Clio、Intapp 與 Thomson Reuters，已由大型律所進行保密測試。", signal: "通用模型業者沒有繞過既有法律科技，反而透過整合進入；真正護城河可能是權威資料、權限與工作流，而非單一聊天介面。", industryImpact: "台灣法律、金融與製造軟體商應掌握本地權威資料、權限控管與稽核流程，以可替換模型的垂直平台對抗通用模型下沉。", date: "09.17", source: "Reuters", region: "北美", impact: "中", url: "https://www.reuters.com/legal/litigation/openai-launches-legal-focused-ai-platform-escalating-race-law-firm-users-2026-09-17/", category: "AI" },
    { title: "OpenAI 五年現金消耗估近 2,800 億美元，算力承諾逼近 8,560 億美元", summary: "Financial Times 報導，OpenAI 預估 2026 至 2030 年累計現金消耗接近 2,800 億美元，同期算力支出承諾約 8,560 億美元；收入則預計由 2026 年 360 億美元增至 2030 年 3,500 億美元。", signal: "模型需求高速成長仍可能伴隨更快的資本消耗；AI 基礎設施訂單看似確定，但最終信用風險集中在少數模型公司的融資與營收假設。", industryImpact: "台灣晶片、伺服器、電源與散熱供應商應分散終端客戶，將預付款、產能保證、資產再利用與信用風險納入長約。", date: "09.19", source: "Financial Times", region: "全球", impact: "高", url: "https://www.ft.com/content/6011d061-eee3-4193-b3b7-8ee4155f538c", category: "AI" },
  ],
  uav: [
    { title: "Anduril：美國延宕 140 億美元對台軍售，已影響無人機業務", summary: "Anduril 表示，美國暫緩包含 Altius 無人機在內的對台軍售案，已影響公司營運；案子並涉及與台灣企業共同製造，延宕被視為與更大範圍對中談判相連。", signal: "友岸合作不只受技術或產能限制，也可能被高層外交談判卡住；採購核准本身成為供應鏈交付風險。", industryImpact: "台灣應以分批授權、共同規格、在地替代料與雙軌商規／軍規產線降低政治等待成本，並把技轉與維保納入採購節點。", date: "09.19", source: "Reuters", region: "亞洲", impact: "高", url: "https://www.reuters.com/world/china/defence-firm-anduril-says-us-delay-taiwan-arms-sales-affecting-its-business-2026-09-19/", category: "UAV" },
    { title: "匈牙利擴建歐洲民用重型無人機工廠，年產能上看 3,500 架", summary: "ABZ Innovation 投資約 700 萬歐元擴建農業與工業重型無人機廠，單班年產 2,000 架、雙班可達 3,500 架，產品已銷往逾 40 國，目標降低歐洲對中國供應的依賴。", signal: "非紅供應鏈的先行市場可能不是軍用，而是農業與工業重型機；民用訂單先建立產線、維修網與規模成本，再支撐戰略自主。", industryImpact: "台灣馬達、ESC、電池與複材廠可切入歐洲重載平台，但需提出 CE／環境可靠度、批次追溯、區域備件與產能切換證據。", date: "09.17", source: "Reuters", region: "歐洲", impact: "高", url: "https://www.reuters.com/business/hungary-expands-civilian-drone-factory-boost-eu-production-2026-09-17/", category: "UAV" },
    { title: "NATO 支持邊緣小模型，讓無人機斷訊後仍能辨識與選擇目標", summary: "瑞典 Scaleout 以小型 AI 模型與聯邦學習支援 ALMA 低成本自主攻擊無人機，使其在通訊中斷或受干擾時仍可於機上進行偵察、辨識與任務決策。", signal: "蜂群自主未必需要最大的模型；小模型加分散學習更符合頻寬、功耗與保密限制，也把資料治理直接推到邊緣節點。", industryImpact: "台灣應整合低功耗 NPU、抗干擾資料鏈、可驗證模型更新與人機授權邊界，將動力平台升級為含運算與任務安全的模組。", date: "09.17", source: "Ars Technica", region: "歐洲", impact: "高", url: "https://arstechnica.com/ai/2026/09/nato-backed-startup-adapts-ai-for-autonomous-drone-recon-and-attack-missions/", category: "UAV" },
    { title: "法國要求全國關鍵基礎設施整備無人機與網攻混合威脅", summary: "法國政府要求相關部門提出保護能源、交通及其他關鍵設施的應變方案，以因應無人機侵入、網路攻擊與破壞行動可能串聯的混合威脅。", signal: "實體無人機與數位入侵不再能分開演練；攻擊者可先以網攻癱瘓感測或指管，再以低成本飛行器製造實體效果。", industryImpact: "台灣應把 C-UAS、OT 資安、備援通訊與事件指揮做成聯合演練，要求感測器、攔截器與資安平台共用時間戳和證據格式。", date: "09.18", source: "Reuters", region: "歐洲", impact: "高", url: "https://www.reuters.com/world/europe/france-prepares-react-russian-hybrid-threats-intensify-2026-09-18/", category: "UAV" },
    { title: "阿拉斯加完成 1,000 公里重載無人機運送血液樣本測試", summary: "國際檢測機構 ITA 完成跨越約 1,000 公里的無人機運輸試驗，持續記錄溫度、濕度、壓力、振動與加速度，評估偏遠地區血液樣本在長距離飛行後的生物標記可靠度。", signal: "商用無人機的核心 KPI 不是飛到多遠，而是貨物在全程是否仍可被信任；環境紀錄與鏈結保全可能比飛行性能更決定監管接受度。", industryImpact: "台灣可把冷鏈感測、震動隔離、電子封條、飛行紀錄與醫療品質系統整合為高價值物流艙，切入離島醫療與跨海檢體運輸。", date: "09.16", source: "Reuters", region: "北美", impact: "中", url: "https://www.reuters.com/sports/ita-completes-1000-km-drone-test-alaska-2026-09-16/", category: "UAV" },
  ],
  robot: [
    { title: "Toyota 估 2028 年起每年投入 64 億美元工廠自動化", summary: "Toyota 預估自 2028 年起每年投入約 64 億美元，在 Toyota、集團公司及供應商部署約 40 萬台工業、物流、人機協作與人形／非人形機器人。", signal: "最大的人形機器人需求故事，可能以混合機器人車隊而非單一人形平台落地；企業會按任務選機型，不會為『像人』本身付費。", industryImpact: "台灣應發展跨機型控制、車規關節驅動、AMR、機器視覺與系統整合，並準備 Toyota 式品質、功能安全與長期供貨證據。", date: "09.18", source: "Reuters", region: "亞洲", impact: "高", url: "https://www.reuters.com/business/autos-transportation/toyota-estimates-factory-automation-could-cost-64-billion-per-year-2028-2026-09-18/", category: "Robot" },
    { title: "Spirit AI：2027 年機器人『大腦』突破，瓶頸在真實資料", summary: "Spirit AI 表示 Moz1 在簡單任務成功率約 90%，並透過約 1,000 名承包者蒐集真實操作資料；數十台機器人已部署於 CATL 與京東，累計募資 6.7 億美元、估值約 29 億美元。", signal: "看似普通的柔性線纜會讓模擬失效；Physical AI 最難的資料往往來自摩擦、變形與失敗復原，而不是更乾淨的合成環境。", industryImpact: "台灣工廠可建立跨企業匿名資料池，標準化力矩、觸覺、電流與失敗標籤，將複雜裝配場域變成模型與關節模組的驗證資產。", date: "09.18", source: "Reuters", region: "亞洲", impact: "高", url: "https://www.reuters.com/world/asia-pacific/founder-chinese-startup-spirit-ai-says-robot-brains-set-2027-breakthrough-2026-09-18/", category: "Robot" },
    { title: "Boston Dynamics 2027 年 IPO 可能性低，規模化與獲利仍未過關", summary: "公司主管表示 2027 年上市可能性不高；Boston Dynamics 尚未獲利或大規模生產，雖規劃 2028 年啟用年產 3 萬台工廠，2021 至 2025 年累計虧損約 1.7 兆韓元。", signal: "全球最知名、技術最成熟的機器人品牌之一，仍可能被量產成本與商業化節奏拖慢；示範領先不等於 IPO 準備度。", industryImpact: "台灣供應商應用量產良率、維保成本、工作時數與回購率審視客戶，不以品牌聲量或示範影片替代信用與需求驗證。", date: "09.14", source: "Reuters", region: "北美", impact: "高", url: "https://www.reuters.com/business/media-telecom/ipo-humanoid-robot-maker-boston-dynamics-unlikely-2027-executive-says-2026-09-14/", category: "Robot" },
    { title: "Swarmer 擬以最高 2.24 億美元收購地面機器人商 Ratel", summary: "烏克蘭自主系統軟體商 Swarmer 將收購 UGV 業者 Ratel；其地面平台除補給與撤離外，也能成為無人機、攔截器及防空載荷的移動發射節點。", signal: "空中與地面機器人正由分立產品合併成系統；UGV 的價值不只在移動，而在成為可分散、可重組的無人載具母平台。", industryImpact: "台灣可整合 UGV 底盤、抗震驅動、供電、資料鏈與 UAV 發射／回收介面，建立海岸、廠區及災防共用的跨域平台。", date: "09.16", source: "Axios", region: "歐洲", impact: "中", url: "https://www.axios.com/2026/09/16/swarmer-ratel-drones-erik-prince", category: "Robot" },
    { title: "OpenAI 以最高 50 萬美元年薪擴編機器人工程團隊", summary: "OpenAI 的機器人職缺由 5 月約 11 個增至 27 個，涵蓋致動器設計、韌體、資料蒐集與分散式訓練資料基礎設施，顯示公司正建立自有機器人設計能力。", signal: "前沿模型公司跨入實體 AI 時，稀缺人才不是提示工程，而是致動器、韌體與資料管線；Physical AI 的競爭重新回到硬體細節。", industryImpact: "台灣精密機械與電子業應把關節、馬達、驅動器、韌體與遙測資料打包，並以共同開發、參考設計及人才留任對接模型公司。", date: "09.19", source: "Business Insider", region: "北美", impact: "高", url: "https://www.businessinsider.com/openai-is-offering-robotics-engineers-up-to-500-000-in-salary-2026-9", category: "Robot" },
  ],
};

export const allNews = [...news.ai, ...news.uav, ...news.robot];
