"use client";
import { useMemo, useState } from "react"; import { Shell, TrendChart } from "../components"; import { allNews, type Category } from "../data";
export function Dashboard(){
  const [category,setCategory]=useState<"全部"|Category>("全部"); const [region,setRegion]=useState("全部"); const [impact,setImpact]=useState("全部");
  const filtered=useMemo(()=>allNews.filter(n=>(category==="全部"||n.category===category)&&(region==="全部"||n.region===region)&&(impact==="全部"||n.impact===impact)),[category,region,impact]);
  return <Shell active="dashboard"><section className="dashboard-head"><div><p className="eyebrow">INTERACTIVE INTELLIGENCE</p><h1>產業趨勢 Dashboard</h1><p>使用產業、地區與影響程度篩選本週情報。</p></div><div className="update-pill"><i/>資料更新<br/><b>2026.09.05 14:00</b></div></section>
    <section className="dashboard-wrap"><div className="filters" aria-label="新聞篩選器"><label>產業分類<select aria-label="產業分類" value={category} onChange={e=>setCategory(e.target.value as "全部"|Category)}><option>全部</option><option>AI</option><option>UAV</option><option>Robot</option></select></label><label>地區<select aria-label="地區" value={region} onChange={e=>setRegion(e.target.value)}><option>全部</option><option>北美</option><option>亞洲</option><option>歐洲</option><option>全球</option></select></label><label>影響程度<select aria-label="影響程度" value={impact} onChange={e=>setImpact(e.target.value)}><option>全部</option><option>高</option><option>中</option></select></label><button onClick={()=>{setCategory("全部");setRegion("全部");setImpact("全部")}}>重設篩選</button></div>
      <div className="dashboard-kpis"><div><span>收錄情報</span><strong>{filtered.length}</strong><small>則</small></div><div><span>高影響事件</span><strong>{filtered.filter(n=>n.impact==="高").length}</strong><small>則</small></div><div><span>主要市場</span><strong>{new Set(filtered.map(n=>n.region)).size}</strong><small>區</small></div><div><span>訊號指數</span><strong>{Math.min(99,64+filtered.length*2.35).toFixed(0)}</strong><small>/100</small></div></div>
      <div className="dashboard-grid"><TrendChart/><div className="distribution-card"><div><h2>情報分布</h2><span>依產業分類</span></div>{(["AI","UAV","Robot"] as Category[]).map((c,i)=>{const count=filtered.filter(n=>n.category===c).length;return <div className="dist-row" key={c}><span>{c}</span><div><i style={{width:`${Math.max(4,count/Math.max(1,filtered.length)*100)}%`}} className={`dist-${i}`}/></div><b>{count}</b></div>})}</div></div>
      <section className="dashboard-table"><div className="section-heading"><div><span className="heading-line"/><h2>篩選結果</h2></div><span>{filtered.length} RESULTS</span></div><div className="table-head"><span>日期</span><span>分類</span><span>標題與摘要</span><span>地區</span><span>影響</span></div>{filtered.map(n=><a className="table-row" key={n.title} href={n.url} target="_blank" rel="noreferrer"><span>{n.date}</span><span className={`category-tag ${n.category.toLowerCase()}`}>{n.category}</span><span><b>{n.title}</b><small>{n.summary}</small></span><span>{n.region}</span><span className={n.impact==="高"?"impact high":"impact"}>{n.impact}</span></a>)}{!filtered.length&&<div className="empty-state">目前沒有符合條件的情報，請調整篩選器。</div>}</section>
    </section></Shell>}
